<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // проверка секретного заголовка от Telegram
    'safe_mode' => env('TELEGRAM_SAFE_MODE', true),

    // Extra or specific configurations
    'config' => [
        'timeout' => (int) env('TELEGRAM_TIMEOUT', 30),
        'client' => array_filter([
            'proxy' => env('TELEGRAM_PROXY'),
        ]),
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
